[terminal.shell]
program = "/bin/zsh"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
