return {
  c = true,
  cpp = true,
  python = true,
  javascript = true,
  typescript = false,
  rust = false,
  lua = true,
  bash = true,
  html = true,
  css = true,
  json = true,
  yaml = true,
  toml = true,
  markdown = true,
  cmake = true,
  jinja = true,
  jsonnet = true,
  docker = true,
  zsh = true,
}
